### ISSUE TITLE
USER and PASSWORD

### ISSUE THREAD

**Issue by yomuevans** [dixant/parking-management#1]
Am new to this, how do you login? whats the default user and password

**Comment by dixanttamda** [comment]
Hi @yomuevans 

You need to put some default users in the database. Please sign in to MongoDB (https://account.mongodb.com/account/login).

- [ ] You can log in with your Gmail account and 

- [ ] create a Project (PARKING-MANAGEMENT) > Cluster0 >  Database(parkingMgmt) > table having name "user" and some default data there as below:

```
{
"_id":{"$oid":"5e8982b333580c2c55446bf7"},
"_userId":{"$numberInt":"1"},"
name":"dixant sharma",
"email":"dixantsharma095@gmail.com",
"password":"1234",
"type":"agent"
}
{
"_id":{"$oid":"5e89839b33580c2c5544b28a"},
"_userId":{"$numberInt":"2"},
"name":"ravi jain",
"email":"ravijain@gmail.com",
"password":"1234",
"type":"assistant"
}
```
**If you are going to use your own DB then you need to replace below the line in src/server.js file** (replace <> data with your own dbuser, password and DB name):
`const dbUri = "mongodb+srv://<DBuser>:<password>@cluster0-bdc8i.mongodb.net/<dbname>?retryWrites=true&w=majority"`

**Or If you want to use my database then you just use below email and password to log in.**

> _Agent type_

`"email":"dixantsharma095@gmail.com",
"password":"1234"`

> _Assistant type_

`"email":"ravijain@gmail.com",
"password":"1234"`

Once you get login successfully, all other tables would be created automatically when you use them like creating parking spaces, etc.

Please let me know if you get any issues in between.

Thanks,
Dixant Sharma

**Comment by dixanttamda** [comment]
Closing this issue. Hope you have got your answer.

**Comment by yomuevans** [comment]
Oh yes, Thank you
